// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/mobile_phone_only_menu/internal/consts"
	"github.com/mbatimel/mobile_phone_only_menu/pkg/interfaces/publicapi"
)

type serverPublicApi struct {
	svc                publicapi.PublicApi
	createDish         PublicApiCreateDish
	markFavoriteDish   PublicApiMarkFavoriteDish
	markUnFavoriteDish PublicApiMarkUnFavoriteDish
	deleteDish         PublicApiDeleteDish
	createChef         PublicApiCreateChef
	deleteChef         PublicApiDeleteChef
	getChef            PublicApiGetChef
	updateDish         PublicApiUpdateDish
	getAllDish         PublicApiGetAllDish
	getFavoriteDish    PublicApiGetFavoriteDish
	deleteAllMenu      PublicApiDeleteAllMenu
}

type MiddlewareSetPublicApi interface {
	Wrap(m MiddlewarePublicApi)
	WrapCreateDish(m MiddlewarePublicApiCreateDish)
	WrapMarkFavoriteDish(m MiddlewarePublicApiMarkFavoriteDish)
	WrapMarkUnFavoriteDish(m MiddlewarePublicApiMarkUnFavoriteDish)
	WrapDeleteDish(m MiddlewarePublicApiDeleteDish)
	WrapCreateChef(m MiddlewarePublicApiCreateChef)
	WrapDeleteChef(m MiddlewarePublicApiDeleteChef)
	WrapGetChef(m MiddlewarePublicApiGetChef)
	WrapUpdateDish(m MiddlewarePublicApiUpdateDish)
	WrapGetAllDish(m MiddlewarePublicApiGetAllDish)
	WrapGetFavoriteDish(m MiddlewarePublicApiGetFavoriteDish)
	WrapDeleteAllMenu(m MiddlewarePublicApiDeleteAllMenu)

	WithMetrics()
	WithLog()
}

func newServerPublicApi(svc publicapi.PublicApi) *serverPublicApi {
	return &serverPublicApi{
		createChef:         svc.CreateChef,
		createDish:         svc.CreateDish,
		deleteAllMenu:      svc.DeleteAllMenu,
		deleteChef:         svc.DeleteChef,
		deleteDish:         svc.DeleteDish,
		getAllDish:         svc.GetAllDish,
		getChef:            svc.GetChef,
		getFavoriteDish:    svc.GetFavoriteDish,
		markFavoriteDish:   svc.MarkFavoriteDish,
		markUnFavoriteDish: svc.MarkUnFavoriteDish,
		svc:                svc,
		updateDish:         svc.UpdateDish,
	}
}

func (srv *serverPublicApi) Wrap(m MiddlewarePublicApi) {
	srv.svc = m(srv.svc)
	srv.createDish = srv.svc.CreateDish
	srv.markFavoriteDish = srv.svc.MarkFavoriteDish
	srv.markUnFavoriteDish = srv.svc.MarkUnFavoriteDish
	srv.deleteDish = srv.svc.DeleteDish
	srv.createChef = srv.svc.CreateChef
	srv.deleteChef = srv.svc.DeleteChef
	srv.getChef = srv.svc.GetChef
	srv.updateDish = srv.svc.UpdateDish
	srv.getAllDish = srv.svc.GetAllDish
	srv.getFavoriteDish = srv.svc.GetFavoriteDish
	srv.deleteAllMenu = srv.svc.DeleteAllMenu
}

func (srv *serverPublicApi) CreateDish(ctx context.Context, secretId uuid.UUID, dish string, category string) (err error) {
	return srv.createDish(ctx, secretId, dish, category)
}

func (srv *serverPublicApi) MarkFavoriteDish(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error) {
	return srv.markFavoriteDish(ctx, secretId, ids)
}

func (srv *serverPublicApi) MarkUnFavoriteDish(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error) {
	return srv.markUnFavoriteDish(ctx, secretId, ids)
}

func (srv *serverPublicApi) DeleteDish(ctx context.Context, secretId uuid.UUID, id uint64) (err error) {
	return srv.deleteDish(ctx, secretId, id)
}

func (srv *serverPublicApi) CreateChef(ctx context.Context, secretId uuid.UUID, name string) (err error) {
	return srv.createChef(ctx, secretId, name)
}

func (srv *serverPublicApi) DeleteChef(ctx context.Context, secretId uuid.UUID) (err error) {
	return srv.deleteChef(ctx, secretId)
}

func (srv *serverPublicApi) GetChef(ctx context.Context, secretId uuid.UUID) (name string, err error) {
	return srv.getChef(ctx, secretId)
}

func (srv *serverPublicApi) UpdateDish(ctx context.Context, secretId uuid.UUID, id uint64, text string, category string) (err error) {
	return srv.updateDish(ctx, secretId, id, text, category)
}

func (srv *serverPublicApi) GetAllDish(ctx context.Context, secretId uuid.UUID, date time.Time) (resp []consts.MenuDish, err error) {
	return srv.getAllDish(ctx, secretId, date)
}

func (srv *serverPublicApi) GetFavoriteDish(ctx context.Context, secretId uuid.UUID, date time.Time) (resp []consts.MenuDish, err error) {
	return srv.getFavoriteDish(ctx, secretId, date)
}

func (srv *serverPublicApi) DeleteAllMenu(ctx context.Context, secretId uuid.UUID) (err error) {
	return srv.deleteAllMenu(ctx, secretId)
}

func (srv *serverPublicApi) WrapCreateDish(m MiddlewarePublicApiCreateDish) {
	srv.createDish = m(srv.createDish)
}

func (srv *serverPublicApi) WrapMarkFavoriteDish(m MiddlewarePublicApiMarkFavoriteDish) {
	srv.markFavoriteDish = m(srv.markFavoriteDish)
}

func (srv *serverPublicApi) WrapMarkUnFavoriteDish(m MiddlewarePublicApiMarkUnFavoriteDish) {
	srv.markUnFavoriteDish = m(srv.markUnFavoriteDish)
}

func (srv *serverPublicApi) WrapDeleteDish(m MiddlewarePublicApiDeleteDish) {
	srv.deleteDish = m(srv.deleteDish)
}

func (srv *serverPublicApi) WrapCreateChef(m MiddlewarePublicApiCreateChef) {
	srv.createChef = m(srv.createChef)
}

func (srv *serverPublicApi) WrapDeleteChef(m MiddlewarePublicApiDeleteChef) {
	srv.deleteChef = m(srv.deleteChef)
}

func (srv *serverPublicApi) WrapGetChef(m MiddlewarePublicApiGetChef) {
	srv.getChef = m(srv.getChef)
}

func (srv *serverPublicApi) WrapUpdateDish(m MiddlewarePublicApiUpdateDish) {
	srv.updateDish = m(srv.updateDish)
}

func (srv *serverPublicApi) WrapGetAllDish(m MiddlewarePublicApiGetAllDish) {
	srv.getAllDish = m(srv.getAllDish)
}

func (srv *serverPublicApi) WrapGetFavoriteDish(m MiddlewarePublicApiGetFavoriteDish) {
	srv.getFavoriteDish = m(srv.getFavoriteDish)
}

func (srv *serverPublicApi) WrapDeleteAllMenu(m MiddlewarePublicApiDeleteAllMenu) {
	srv.deleteAllMenu = m(srv.deleteAllMenu)
}

func (srv *serverPublicApi) WithMetrics() {
	srv.Wrap(metricsMiddlewarePublicApi)
}

func (srv *serverPublicApi) WithLog() {
	srv.Wrap(loggerMiddlewarePublicApi())
}
