// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/mobile_phone_only_menu/internal/consts"
	"github.com/mbatimel/mobile_phone_only_menu/pkg/interfaces/publicapi"
)

type PublicApiCreateDish func(ctx context.Context, secretId uuid.UUID, dish string, category string) (err error)
type PublicApiMarkFavoriteDish func(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error)
type PublicApiMarkUnFavoriteDish func(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error)
type PublicApiDeleteDish func(ctx context.Context, secretId uuid.UUID, id uint64) (err error)
type PublicApiCreateChef func(ctx context.Context, secretId uuid.UUID, name string) (err error)
type PublicApiDeleteChef func(ctx context.Context, secretId uuid.UUID) (err error)
type PublicApiGetChef func(ctx context.Context, secretId uuid.UUID) (name string, err error)
type PublicApiUpdateDish func(ctx context.Context, secretId uuid.UUID, id uint64, text string, category string) (err error)
type PublicApiGetAllDish func(ctx context.Context, secretId uuid.UUID) (resp []consts.MenuDish, err error)
type PublicApiGetFavoriteDish func(ctx context.Context, secretId uuid.UUID) (resp []consts.MenuDish, err error)
type PublicApiDeleteAllMenu func(ctx context.Context, secretId uuid.UUID) (err error)

type MiddlewarePublicApi func(next publicapi.PublicApi) publicapi.PublicApi

type MiddlewarePublicApiCreateDish func(next PublicApiCreateDish) PublicApiCreateDish
type MiddlewarePublicApiMarkFavoriteDish func(next PublicApiMarkFavoriteDish) PublicApiMarkFavoriteDish
type MiddlewarePublicApiMarkUnFavoriteDish func(next PublicApiMarkUnFavoriteDish) PublicApiMarkUnFavoriteDish
type MiddlewarePublicApiDeleteDish func(next PublicApiDeleteDish) PublicApiDeleteDish
type MiddlewarePublicApiCreateChef func(next PublicApiCreateChef) PublicApiCreateChef
type MiddlewarePublicApiDeleteChef func(next PublicApiDeleteChef) PublicApiDeleteChef
type MiddlewarePublicApiGetChef func(next PublicApiGetChef) PublicApiGetChef
type MiddlewarePublicApiUpdateDish func(next PublicApiUpdateDish) PublicApiUpdateDish
type MiddlewarePublicApiGetAllDish func(next PublicApiGetAllDish) PublicApiGetAllDish
type MiddlewarePublicApiGetFavoriteDish func(next PublicApiGetFavoriteDish) PublicApiGetFavoriteDish
type MiddlewarePublicApiDeleteAllMenu func(next PublicApiDeleteAllMenu) PublicApiDeleteAllMenu
