// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/mobile_phone_only_menu/pkg/interfaces/publicapi"
)

type httpPublicApi struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverPublicApi
	base             publicapi.PublicApi
}

func NewPublicApi(svcPublicApi publicapi.PublicApi) (srv *httpPublicApi) {

	srv = &httpPublicApi{
		base: svcPublicApi,
		svc:  newServerPublicApi(svcPublicApi),
	}
	return
}

func (http *httpPublicApi) Service() *serverPublicApi {
	return http.svc
}

func (http *httpPublicApi) WithLog() *httpPublicApi {
	http.svc.WithLog()
	return http
}

func (http *httpPublicApi) WithMetrics() *httpPublicApi {
	http.svc.WithMetrics()
	return http
}

func (http *httpPublicApi) WithErrorHandler(handler ErrorHandler) *httpPublicApi {
	http.errorHandler = handler
	return http
}

func (http *httpPublicApi) SetRoutes(route *fiber.App) {
	route.Post("/menu/api/create/dish", http.serveCreateDish)
	route.Post("/menu/api/mark", http.serveMarkFavoriteDish)
	route.Post("/menu/api/unmark", http.serveMarkUnFavoriteDish)
	route.Delete("/menu/api/delete", http.serveDeleteDish)
	route.Post("/menu/api/create/chef", http.serveCreateChef)
	route.Delete("/menu/api/chef", http.serveDeleteChef)
	route.Put("/menu/api/update", http.serveUpdateDish)
	route.Get("/menu/api/all", http.serveGetAllDish)
	route.Get("/menu/api/favorite", http.serveGetFavoriteDish)
	route.Delete("/menu/api/all", http.serveDeleteAllMenu)
}
