// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/mobile_phone_only_menu/internal/consts"
	"github.com/mbatimel/mobile_phone_only_menu/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/mobile_phone_only_menu/pkg/interfaces/publicapi"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerPublicApi struct {
	next publicapi.PublicApi
}

func loggerMiddlewarePublicApi() MiddlewarePublicApi {
	return func(next publicapi.PublicApi) publicapi.PublicApi {
		return &loggerPublicApi{next: next}
	}
}

func (m loggerPublicApi) CreateDish(ctx context.Context, secretId uuid.UUID, dish string, category string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "createDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.createDish",
				"request": viewer.Sprintf("%+v", requestPublicApiCreateDish{
					Category: category,
					Dish:     dish,
					SecretId: secretId,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiCreateDish{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call createDish")
	}(time.Now())
	return m.next.CreateDish(ctx, secretId, dish, category)
}

func (m loggerPublicApi) MarkFavoriteDish(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "markFavoriteDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.markFavoriteDish",
				"request": viewer.Sprintf("%+v", requestPublicApiMarkFavoriteDish{
					Ids:      ids,
					SecretId: secretId,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiMarkFavoriteDish{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call markFavoriteDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call markFavoriteDish")
	}(time.Now())
	return m.next.MarkFavoriteDish(ctx, secretId, ids)
}

func (m loggerPublicApi) MarkUnFavoriteDish(ctx context.Context, secretId uuid.UUID, ids []uint64) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "markUnFavoriteDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.markUnFavoriteDish",
				"request": viewer.Sprintf("%+v", requestPublicApiMarkUnFavoriteDish{
					Ids:      ids,
					SecretId: secretId,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiMarkUnFavoriteDish{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call markUnFavoriteDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call markUnFavoriteDish")
	}(time.Now())
	return m.next.MarkUnFavoriteDish(ctx, secretId, ids)
}

func (m loggerPublicApi) DeleteDish(ctx context.Context, secretId uuid.UUID, id uint64) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "deleteDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.deleteDish",
				"request": viewer.Sprintf("%+v", requestPublicApiDeleteDish{
					Id:       id,
					SecretId: secretId,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiDeleteDish{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteDish")
	}(time.Now())
	return m.next.DeleteDish(ctx, secretId, id)
}

func (m loggerPublicApi) CreateChef(ctx context.Context, secretId uuid.UUID, name string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "createChef").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.createChef",
				"request": viewer.Sprintf("%+v", requestPublicApiCreateChef{
					Name:     name,
					SecretId: secretId,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiCreateChef{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createChef")
			return
		}
		logger.Info().Func(logHandle).Msg("call createChef")
	}(time.Now())
	return m.next.CreateChef(ctx, secretId, name)
}

func (m loggerPublicApi) DeleteChef(ctx context.Context, secretId uuid.UUID) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "deleteChef").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "publicApi.deleteChef",
				"request":  viewer.Sprintf("%+v", requestPublicApiDeleteChef{SecretId: secretId}),
				"response": viewer.Sprintf("%+v", responsePublicApiDeleteChef{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteChef")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteChef")
	}(time.Now())
	return m.next.DeleteChef(ctx, secretId)
}

func (m loggerPublicApi) GetChef(ctx context.Context, secretId uuid.UUID) (name string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "getChef").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "publicApi.getChef",
				"request":  viewer.Sprintf("%+v", requestPublicApiGetChef{SecretId: secretId}),
				"response": viewer.Sprintf("%+v", responsePublicApiGetChef{Name: name}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getChef")
			return
		}
		logger.Info().Func(logHandle).Msg("call getChef")
	}(time.Now())
	return m.next.GetChef(ctx, secretId)
}

func (m loggerPublicApi) UpdateDish(ctx context.Context, secretId uuid.UUID, id uint64, text string, category string) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "updateDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "publicApi.updateDish",
				"request": viewer.Sprintf("%+v", requestPublicApiUpdateDish{
					Category: category,
					Id:       id,
					SecretId: secretId,
					Text:     text,
				}),
				"response": viewer.Sprintf("%+v", responsePublicApiUpdateDish{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateDish")
	}(time.Now())
	return m.next.UpdateDish(ctx, secretId, id, text, category)
}

func (m loggerPublicApi) GetAllDish(ctx context.Context, secretId uuid.UUID) (resp []consts.MenuDish, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "getAllDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "publicApi.getAllDish",
				"request":  viewer.Sprintf("%+v", requestPublicApiGetAllDish{SecretId: secretId}),
				"response": viewer.Sprintf("%+v", responsePublicApiGetAllDish{Resp: resp}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getAllDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call getAllDish")
	}(time.Now())
	return m.next.GetAllDish(ctx, secretId)
}

func (m loggerPublicApi) GetFavoriteDish(ctx context.Context, secretId uuid.UUID) (resp []consts.MenuDish, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "getFavoriteDish").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "publicApi.getFavoriteDish",
				"request":  viewer.Sprintf("%+v", requestPublicApiGetFavoriteDish{SecretId: secretId}),
				"response": viewer.Sprintf("%+v", responsePublicApiGetFavoriteDish{Resp: resp}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getFavoriteDish")
			return
		}
		logger.Info().Func(logHandle).Msg("call getFavoriteDish")
	}(time.Now())
	return m.next.GetFavoriteDish(ctx, secretId)
}

func (m loggerPublicApi) DeleteAllMenu(ctx context.Context, secretId uuid.UUID) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "PublicApi").Str("method", "deleteAllMenu").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "publicApi.deleteAllMenu",
				"request":  viewer.Sprintf("%+v", requestPublicApiDeleteAllMenu{SecretId: secretId}),
				"response": viewer.Sprintf("%+v", responsePublicApiDeleteAllMenu{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteAllMenu")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteAllMenu")
	}(time.Now())
	return m.next.DeleteAllMenu(ctx, secretId)
}
