// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/mobile_phone_only_menu/internal/consts"
)

type requestPublicApiCreateDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Dish     string    `json:"dish,omitempty"`
	Categoty string    `json:"categoty,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiCreateDish struct{}

type requestPublicApiMarkFavoriteDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Ids      []uint64  `json:"ids,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiMarkFavoriteDish struct{}

type requestPublicApiMarkUnFavoriteDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Ids      []uint64  `json:"ids,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiMarkUnFavoriteDish struct{}

type requestPublicApiDeleteDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Id       uint64    `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiDeleteDish struct{}

type requestPublicApiCreateChef struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Name     string    `json:"name,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiCreateChef struct{}

type requestPublicApiDeleteChef struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiDeleteChef struct{}

type requestPublicApiUpdateDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
	Id       uint64    `json:"id,omitempty"`
	Text     string    `json:"text,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiUpdateDish struct{}

type requestPublicApiGetAllDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
}

type responsePublicApiGetAllDish struct {
	Resp []consts.MenuDish `json:"resp,omitempty"`
}

type requestPublicApiGetFavoriteDish struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
}

type responsePublicApiGetFavoriteDish struct {
	Resp []consts.MenuDish `json:"resp,omitempty"`
}

type requestPublicApiDeleteAllMenu struct {
	SecretId uuid.UUID `json:"secretId,omitempty"`
}

// Formal exchange type, please do not delete.
type responsePublicApiDeleteAllMenu struct{}
