// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
	customhandlers "github.com/mbatimel/mobile_phone_only_menu/internal/transport/http/custom-handlers"
)

func (http *httpPublicApi) createDish(ctx context.Context, request requestPublicApiCreateDish) (response responsePublicApiCreateDish, err error) {

	err = http.svc.CreateDish(ctx, request.SecretId, request.Dish, request.Category)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveCreateDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiCreateDish
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.CreateDish(ctx, http.svc, request.SecretId, request.Dish, request.Category)
}
func (http *httpPublicApi) markFavoriteDish(ctx context.Context, request requestPublicApiMarkFavoriteDish) (response responsePublicApiMarkFavoriteDish, err error) {

	err = http.svc.MarkFavoriteDish(ctx, request.SecretId, request.Ids)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveMarkFavoriteDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiMarkFavoriteDish
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.MarkFavoriteDish(ctx, http.svc, request.SecretId, request.Ids)
}
func (http *httpPublicApi) markUnFavoriteDish(ctx context.Context, request requestPublicApiMarkUnFavoriteDish) (response responsePublicApiMarkUnFavoriteDish, err error) {

	err = http.svc.MarkUnFavoriteDish(ctx, request.SecretId, request.Ids)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveMarkUnFavoriteDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiMarkUnFavoriteDish
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.MarkUnFavoriteDish(ctx, http.svc, request.SecretId, request.Ids)
}
func (http *httpPublicApi) deleteDish(ctx context.Context, request requestPublicApiDeleteDish) (response responsePublicApiDeleteDish, err error) {

	err = http.svc.DeleteDish(ctx, request.SecretId, request.Id)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveDeleteDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiDeleteDish
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.DeleteDish(ctx, http.svc, request.SecretId, request.Id)
}
func (http *httpPublicApi) createChef(ctx context.Context, request requestPublicApiCreateChef) (response responsePublicApiCreateChef, err error) {

	err = http.svc.CreateChef(ctx, request.SecretId, request.Name)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveCreateChef(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiCreateChef
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.CreateChef(ctx, http.svc, request.SecretId, request.Name)
}
func (http *httpPublicApi) deleteChef(ctx context.Context, request requestPublicApiDeleteChef) (response responsePublicApiDeleteChef, err error) {

	err = http.svc.DeleteChef(ctx, request.SecretId)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveDeleteChef(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiDeleteChef

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.DeleteChef(ctx, http.svc, request.SecretId)
}
func (http *httpPublicApi) getChef(ctx context.Context, request requestPublicApiGetChef) (response responsePublicApiGetChef, err error) {

	response.Name, err = http.svc.GetChef(ctx, request.SecretId)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveGetChef(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiGetChef

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.GetChef(ctx, http.svc, request.SecretId)
}
func (http *httpPublicApi) updateDish(ctx context.Context, request requestPublicApiUpdateDish) (response responsePublicApiUpdateDish, err error) {

	err = http.svc.UpdateDish(ctx, request.SecretId, request.Id, request.Text, request.Category)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveUpdateDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiUpdateDish
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.UpdateDish(ctx, http.svc, request.SecretId, request.Id, request.Text, request.Category)
}
func (http *httpPublicApi) getAllDish(ctx context.Context, request requestPublicApiGetAllDish) (response responsePublicApiGetAllDish, err error) {

	response.Resp, err = http.svc.GetAllDish(ctx, request.SecretId, request.Date)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveGetAllDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiGetAllDish

	if _date := ctx.Query("date"); _date != "" {
		var date time.Time
		date, err = time.Parse(time.RFC3339Nano, _date)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Date = date
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.GetAllDish(ctx, http.svc, request.SecretId, request.Date)
}
func (http *httpPublicApi) getFavoriteDish(ctx context.Context, request requestPublicApiGetFavoriteDish) (response responsePublicApiGetFavoriteDish, err error) {

	response.Resp, err = http.svc.GetFavoriteDish(ctx, request.SecretId, request.Date)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveGetFavoriteDish(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiGetFavoriteDish

	if _date := ctx.Query("date"); _date != "" {
		var date time.Time
		date, err = time.Parse(time.RFC3339Nano, _date)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Date = date
	}

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.GetFavoriteDish(ctx, http.svc, request.SecretId, request.Date)
}
func (http *httpPublicApi) deleteAllMenu(ctx context.Context, request requestPublicApiDeleteAllMenu) (response responsePublicApiDeleteAllMenu, err error) {

	err = http.svc.DeleteAllMenu(ctx, request.SecretId)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPublicApi) serveDeleteAllMenu(ctx *fiber.Ctx) (err error) {

	var request requestPublicApiDeleteAllMenu

	if _secretId := ctx.Cookies("x-secret-id"); _secretId != "" {
		var secretId uuid.UUID
		secretId, _ = uuid.Parse(_secretId)
		request.SecretId = secretId
	}

	return customhandlers.DeleteAllMenu(ctx, http.svc, request.SecretId)
}
